name: Mobile CI

on:
  push:
    branches: [ master, "feature/*" ]
  pull_request:
    branches: [ master ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      - name: Grant permission
        run: chmod +x gradlew

      - name: Run Common Tests
        run: ./gradlew :composeApp:testDebugUnitTest

  android-build:
    needs: unit-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      - name: Grant permission
        run: chmod +x gradlew

      - name: Create Google Services JSON
        run: echo '${{ secrets.GOOGLE_SERVICES_JSON }}' > composeApp/google-services.json

      - name: Build Android APK
        run: ./gradlew :composeApp:assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-release
          path: composeApp/build/outputs/apk/debug/*.apk

  ios-build:
    needs: unit-tests
    runs-on: macos-latest
    steps:

      - uses: actions/checkout@v4

      - name: Create Google Services Plist
        run: echo '${{ secrets.GOOGLE_SERVICES_PLIST }}' > iosApp/iosApp/GoogleService-Info.plist

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods

      - name: Clean Pods
        run: |
          cd iosApp
          pod deintegrate || true
          pod cache clean --all || true
          rm -rf Pods Podfile.lock

      - name: Grant permission
        run: chmod +x gradlew

      - name: Clean Gradle
        run: ./gradlew clean

      - name: Build iOS Framework
        run: ./gradlew :composeApp:iosSimulatorArm64Binaries
        env:
          IPHONEOS_DEPLOYMENT_TARGET: "15.0"

      - name: Upload iOS Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-framework
          path: composeApp/build/bin/iosSimulatorArm64/debugFramework/
