name: Mobile CI

on:
  push:
    branches: [ master, "feature/*" ]
  pull_request:
    branches: [ master ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      - name: Grant permission
        run: chmod +x gradlew

      - name: Run Common Tests
        run: ./gradlew :composeApp:testDebugUnitTest

  android-build:
    needs: unit-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create Mock Google Services JSON
        run: |
          echo '{
            "project_info": { "project_number": "123", "project_id": "mock-id" },
            "client": [ { "client_info": { "mobilesdk_app_id": "1:123:android:abc", "android_client_info": { "package_name": "com.example.sharedsocial_kmp" } } } ],
            "configuration_version": "1"
          }' > composeApp/google-services.json

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Grant permission
        run: chmod +x gradlew

      - name: Build Android APK
        run: ./gradlew :composeApp:assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-release
          path: composeApp/build/outputs/apk/release/*.apk

  ios-build:
    needs: unit-tests
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create Mock Firebase Plist
        run: |
          printf '<?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>API_KEY</key> <string>mock_api_key</string>
            <key>GOOGLE_APP_ID</key> <string>1:123:ios:abc</string>
            <key>PROJECT_ID</key> <string>mock-id</string>
          </dict>
          </plist>' > iosApp/iosApp/GoogleService-Info.plist

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      - name: Grant permission
        run: chmod +x gradlew

      - name: Build iOS Framework
        run: ./gradlew :composeApp:iosSimulatorArm64Binaries

      - name: Upload iOS Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-framework
          path: composeApp/build/bin/iosSimulatorArm64/debugFramework/